# Generated by Django 5.0.7 on 2024-09-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('idinstitucion', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut_institucion', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_isntitucion', models.CharField(blank=True, max_length=80, null=True)),
            ],
            options={
                'db_table': 'Convenio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EvaluacionCredito',
            fields=[
                ('id_eva', models.BigAutoField(primary_key=True, serialize=False)),
                ('rut_eva', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_eva', models.CharField(blank=True, max_length=80, null=True)),
                ('telefono_eva', models.CharField(blank=True, max_length=10, null=True)),
                ('correo_eva', models.CharField(blank=True, max_length=80, null=True)),
                ('monto_eva', models.IntegerField(null=True)),
                ('plazo_eva', models.IntegerField(null=True)),
                ('valorCuota_eva', models.IntegerField(null=True)),
                ('tasa_eva', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_primer_venc', models.DateField(blank=True, null=True)),
                ('fecha_simulacion_eva', models.DateField(blank=True, null=True)),
                ('fecha_resolucion_eva', models.DateField(blank=True, null=True)),
                ('estado_eva', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'EvaluacionCredito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario_soc', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_soc', models.CharField(blank=True, max_length=80, null=True)),
                ('apellido_soc', models.CharField(blank=True, max_length=80, null=True)),
                ('rut_soc', models.CharField(blank=True, max_length=10, null=True)),
                ('correo_soc', models.CharField(blank=True, max_length=80, null=True)),
                ('usuario_soc', models.CharField(blank=True, max_length=30, null=True)),
                ('clave_soc', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': True,
            },
        ),
    ]
