# Generated by Django 5.0.7 on 2024-09-29 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacioncredito',
            name='resultado_eva',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacioncredito',
            name='estado_eva',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacioncredito',
            name='fecha_resolucion_eva',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='evaluacioncredito',
            name='fecha_simulacion_eva',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
