# Generated by Django 5.0.7 on 2024-09-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoopApp', '0002_evaluacioncredito_resultado_eva_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacioncredito',
            name='observacion_eva',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
